### ISSUE TITLE
configuration of piwik failed

### ISSUE THREAD

**Issue by rallek** [phaidon/Piwik#19] opened 2014-02-14 20:06 UTC
I have an own subdomain for my piwik like piwik.mydomain.net. I can not configure the piwik module because I do get the following error:
`URL zur Piwik-Installation: Fehler! Ungültige URL.`

Zikula 1.3.6 german / piwik 2.0.3

**Comment by MrMontesa** [comment] 2015-02-23 14:31
Hey,
tried setting up Piwik today as well on one of my sites. I do receive the same error message (URL zur Piwik-Installation: Fehler! Ungültige URL)
Also the links to Piwik to get to know the token & ID do not work any longer.
Here's my environment:
Piwik 2.11.1 (also tested before update with 2.8.?)
Zikula: 1.3.9
Piwik modul: Github master download from today

Let me know how I can help to get this sorted.

**Comment by lmm-git** [comment] 2015-02-23 15:45
Did you tried to put in the URL with leading http:// or https://?
With its working at my server with Piwik 2.11.1 and Zikula 1.3.9

**Comment by MrMontesa** [comment] 2015-02-24 07:53
Thanks for the quick docu update. I was able to get my token now. 
I've tried various ways to enter the URL. None of them worked.
with or w/o http/https in front
with or w/o www in front
Always the same error message: URL zur Piwik-Installation: Fehler! Ungültige URL.
And on top of the page a second one: An error occured. Please check URL and auth token. You need at least view access to one site.

I can confirm that my auth token has admin rights in Piwik.
From the error messages I would think that the problem is either:
- in a URL parser/validator function
or:
- In a test connection attempt towards to Piwik installation which fails.

**Comment by MrMontesa** [comment] 2015-02-24 08:03
I just noticed one more thing:
I saved the settings as I think they are right. Indeed there are red alerts, but it seems they are saved anyway. Then moving to the tab "Problembehebung" I can see in point 3 a link that should direct into my Piwik install. This link is broken and doe not work at all (error 404). The link is:
http://mydomain.de/piwik/index.php?module=SitesManager&action=displayJavascriptCode&idSite=0
Of cors mydomain is my real domain!

Also it references a wrong SiteId of Piwik, as I do have multiple domains tracked with the Piwik installation.
Then I recognized that the SiteId is never queried in the local Piwik config. I've doublechecked one of my existing Piwik installation on  a Zikula 1.2 inastall, there the SiteId is still a mandataory input field.

Hope this helps in tracking down the issue. I guess there might have been changes in Piwik URL scheme

**Comment by lmm-git** [comment] 2015-02-24 20:16
You can try again to configure the piwik module. I tested it on my local machine and it worked... Can you try iit again with my version from https://github.com/lmm-git/Piwik/archive/master.zip

I think the links should be fixed in another PR or issue.

**Closed** 2015-02-24 21:59 UTC
Labels: Bug
